# Generated by Django 3.2.19 on 2023-06-07 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('adventure', 'Adventure'), ('travel', 'Travel'), ('nature', 'Nature'), ('landscape', 'Landscape'), ('aerial', 'Aerial'), ('wildlife', 'Wildlife'), ('street', 'Street'), ('architecture', 'Architecture')], default='travel', max_length=20)),
                ('hashtags', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='../default_post_hc3mjm', upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
