# Generated by Django 3.2.19 on 2023-06-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='exif',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
