# Generated by Django 3.2.19 on 2023-06-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='content',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='equipment',
            field=models.TextField(blank=True, max_length=70),
        ),
    ]
